# Generated by Django 5.0.4 on 2024-04-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeiboNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('user_id', models.CharField(max_length=64, null=True, verbose_name='用户ID')),
                ('nickname', models.CharField(max_length=64, null=True, verbose_name='用户昵称')),
                ('avatar', models.CharField(max_length=255, null=True, verbose_name='用户头像地址')),
                ('gender', models.CharField(max_length=12, null=True, verbose_name='用户性别')),
                ('profile_url', models.CharField(max_length=255, null=True, verbose_name='用户主页地址')),
                ('ip_location', models.CharField(default='发布微博的地理信息', max_length=32, verbose_name='发布微博的地理信息')),
                ('add_ts', models.BigIntegerField(verbose_name='记录添加时间戳')),
                ('last_modify_ts', models.BigIntegerField(verbose_name='记录最后修改时间戳')),
                ('note_id', models.CharField(max_length=64, verbose_name='帖子ID')),
                ('content', models.TextField(null=True, verbose_name='帖子正文内容')),
                ('create_time', models.BigIntegerField(verbose_name='帖子发布时间戳')),
                ('create_date_time', models.CharField(max_length=32, verbose_name='帖子发布日期时间')),
                ('liked_count', models.CharField(max_length=16, null=True, verbose_name='帖子点赞数')),
                ('comments_count', models.CharField(max_length=16, null=True, verbose_name='帖子评论数量')),
                ('shared_count', models.CharField(max_length=16, null=True, verbose_name='帖子转发数量')),
                ('note_url', models.CharField(max_length=512, null=True, verbose_name='帖子详情URL')),
            ],
            options={
                'verbose_name': '微博帖子',
                'verbose_name_plural': '微博帖子',
                'db_table': 'weibo_note',
            },
        ),
        migrations.CreateModel(
            name='WeiboNoteComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('user_id', models.CharField(max_length=64, null=True, verbose_name='用户ID')),
                ('nickname', models.CharField(max_length=64, null=True, verbose_name='用户昵称')),
                ('avatar', models.CharField(max_length=255, null=True, verbose_name='用户头像地址')),
                ('gender', models.CharField(max_length=12, null=True, verbose_name='用户性别')),
                ('profile_url', models.CharField(max_length=255, null=True, verbose_name='用户主页地址')),
                ('ip_location', models.CharField(default='发布微博的地理信息', max_length=32, verbose_name='发布微博的地理信息')),
                ('add_ts', models.BigIntegerField(verbose_name='记录添加时间戳')),
                ('last_modify_ts', models.BigIntegerField(verbose_name='记录最后修改时间戳')),
                ('comment_id', models.CharField(max_length=64, verbose_name='评论ID')),
                ('note_id', models.CharField(max_length=64, verbose_name='帖子ID')),
                ('content', models.TextField(null=True, verbose_name='评论内容')),
                ('create_time', models.BigIntegerField(verbose_name='评论时间戳')),
                ('create_date_time', models.CharField(max_length=32, verbose_name='评论日期时间')),
                ('comment_like_count', models.CharField(max_length=16, verbose_name='评论点赞数量')),
                ('sub_comment_count', models.CharField(max_length=16, verbose_name='评论回复数')),
            ],
            options={
                'verbose_name': '微博帖子评论',
                'verbose_name_plural': '微博帖子评论',
                'db_table': 'weibo_note_comment',
            },
        ),
    ]
