# Generated by Django 5.0.4 on 2024-04-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibonotecomment',
            name='content',
            field=models.CharField(max_length=1000, null=True, verbose_name='评论内容'),
        ),
    ]
