# Generated by Django 5.0.4 on 2024-04-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_weibonotecomment_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCrawl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('note_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '指定博文爬虫',
                'db_table': 'note_id_crawl',
            },
        ),
        migrations.CreateModel(
            name='KeyWordCrawl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('keyword', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('isCrawlComment', models.BooleanField()),
            ],
            options={
                'verbose_name': '关键词爬虫',
                'db_table': 'keyword_crawl',
            },
        ),
    ]
