# Generated by Django 5.0.4 on 2024-04-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_blogcrawl_keywordcrawl'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcrawl',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('doing', 'Doing'), ('done', 'Done')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='keywordcrawl',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('doing', 'Doing'), ('done', 'Done')], default='pending', max_length=10),
        ),
    ]
